# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- feature/*
- release/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
    - task: UseDotNet@2 
      displayName: ".NET Core 3.1.x"
      inputs:
        version: '3.1.x'
        packageType: sdk
    
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

    - script: dotnet publish --output $(Build.BinariesDirectory)/release-artifact
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
      displayName: 'dotnet publish $(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
      inputs:
        PathtoPublish: '$(Build.BinariesDirectory)/release-artifact'
        ArtifactName: 'artifacts'
        publishLocation: 'Container'